# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Request-level planning for connector-independent KV transfers."""

from collections import defaultdict
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from itertools import product

from vllm.distributed.kv_transfer.kv_placement import (
    CanonicalPageMapping,
    KVFormatManifest,
    KVRange,
    LayerPageMapping,
    PagePlacement,
    RankPlacementManifest,
    TransferRun,
    compose_page_placements,
    iter_page_placement_transfer_runs,
    validate_kv_ranges,
)
from vllm.distributed.kv_transfer.transfer_completion import WorkerIdentity


def _require_string(value: str, name: str) -> None:
    if not isinstance(value, str) or not value or value.strip() != value:
        raise ValueError(f"{name} must be a non-empty canonical string")


def _require_nonnegative_int(value: int, name: str) -> None:
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise ValueError(f"{name} must be a non-negative integer")


@dataclass(frozen=True)
class EndpointRoute:
    """Stable deployment generation and DP replica selected for one endpoint."""

    deployment_id: str
    topology_generation: int
    dp_group_id: str
    dp_rank: int

    def __post_init__(self) -> None:
        _require_string(self.deployment_id, "deployment_id")
        _require_nonnegative_int(self.topology_generation, "topology_generation")
        _require_string(self.dp_group_id, "dp_group_id")
        _require_nonnegative_int(self.dp_rank, "dp_rank")


@dataclass(frozen=True)
class LocalPageAllocation:
    """A worker-local page bound to request-wide canonical token coordinates.

    The stable allocation key is ``(worker_id, layer_name, local_page_id)``.
    ``worker_incarnation`` prevents allocator state from an earlier worker
    process from being reused after a restart.
    """

    worker_id: str
    worker_incarnation: str
    layer_name: str
    local_page_id: int
    canonical_page_index: int
    first_token: int
    local_base: int = 0

    def __post_init__(self) -> None:
        _require_string(self.worker_id, "worker_id")
        _require_string(self.worker_incarnation, "worker_incarnation")
        _require_string(self.layer_name, "layer_name")
        _require_nonnegative_int(self.local_page_id, "local_page_id")
        _require_nonnegative_int(self.canonical_page_index, "canonical_page_index")
        _require_nonnegative_int(self.first_token, "first_token")
        _require_nonnegative_int(self.local_base, "local_base")

    @property
    def key(self) -> tuple[str, str, int]:
        """Return the stable worker/layer/page allocation key."""
        return self.worker_id, self.layer_name, self.local_page_id


@dataclass(frozen=True)
class LayerTransferPlan:
    """Direct segmented transfer runs for one model layer."""

    layer_name: str
    layer_index: int
    semantic_group_id: str
    source_group_id: int
    destination_group_id: int
    runs: tuple[TransferRun, ...]


@dataclass(frozen=True)
class RequestTransferPlan:
    """Layer copy plans and all barrier participants for both endpoints."""

    layers: tuple[LayerTransferPlan, ...]
    source_route: EndpointRoute
    destination_route: EndpointRoute
    source_participants: tuple[WorkerIdentity, ...]
    destination_participants: tuple[WorkerIdentity, ...]

    @property
    def source_participant_worker_ids(self) -> tuple[str, ...]:
        """Return source worker IDs independently of generated byte runs."""
        return tuple(item.worker_id for item in self.source_participants)

    @property
    def destination_participant_worker_ids(self) -> tuple[str, ...]:
        """Return destination worker IDs independently of generated byte runs."""
        return tuple(item.worker_id for item in self.destination_participants)

    @property
    def source_expected_participant_count(self) -> int:
        """Return the source-side completion barrier size."""
        return len(self.source_participants)

    @property
    def destination_expected_participant_count(self) -> int:
        """Return the destination-side completion barrier size."""
        return len(self.destination_participants)


@dataclass(frozen=True)
class RequestLayerSpec:
    """Validated layer identity independent of request page allocations."""

    layer_name: str
    layer_index: int
    semantic_group_id: str
    source_group_id: int
    destination_group_id: int


@dataclass(frozen=True)
class RequestTransferContext:
    """Validated endpoint and layer metadata for incremental request planning.

    The context intentionally contains no allocator pages or transfer runs. A
    connector can therefore retain it while presenting bounded page windows to
    :func:`plan_request_transfer_layer`.
    """

    source_format: KVFormatManifest
    destination_format: KVFormatManifest
    source_route: EndpointRoute
    destination_route: EndpointRoute
    source_workers: tuple[RankPlacementManifest, ...]
    destination_workers: tuple[RankPlacementManifest, ...]
    ranges: tuple[KVRange, ...]
    layers: tuple[RequestLayerSpec, ...]
    source_participants: tuple[WorkerIdentity, ...]
    destination_participants: tuple[WorkerIdentity, ...]

    @property
    def source_expected_participant_count(self) -> int:
        """Return the source-side completion barrier size."""
        return len(self.source_participants)

    @property
    def destination_expected_participant_count(self) -> int:
        """Return the destination-side completion barrier size."""
        return len(self.destination_participants)


@dataclass(frozen=True)
class _BoundEndpoint:
    format_manifest: KVFormatManifest
    route: EndpointRoute
    workers: tuple[RankPlacementManifest, ...]
    pages: tuple[LocalPageAllocation, ...]


def _mapping_for_layer(
    worker: RankPlacementManifest, layer_name: str
) -> LayerPageMapping | None:
    for layer_mapping in worker.mappings:
        if layer_mapping.layer_name == layer_name:
            return layer_mapping
    return None


def _bind_endpoint(
    label: str,
    format_manifest: KVFormatManifest,
    route: EndpointRoute,
    workers: Sequence[RankPlacementManifest],
    pages: Sequence[LocalPageAllocation],
) -> _BoundEndpoint:
    workers = tuple(workers)
    pages = tuple(pages)
    if not workers:
        raise ValueError(f"{label} endpoint has no workers")
    if any(not isinstance(worker, RankPlacementManifest) for worker in workers):
        raise ValueError(f"{label} workers must contain RankPlacementManifest values")
    if any(not isinstance(page, LocalPageAllocation) for page in pages):
        raise ValueError(f"{label} pages must contain LocalPageAllocation values")

    workers_by_id: dict[str, RankPlacementManifest] = {}
    for worker in workers:
        if worker.worker_id in workers_by_id:
            raise ValueError(
                f"{label} endpoint advertises duplicate worker {worker.worker_id!r}"
            )
        workers_by_id[worker.worker_id] = worker
        if worker.deployment_id != route.deployment_id:
            raise ValueError(
                f"{label} worker {worker.worker_id!r} belongs to deployment "
                f"{worker.deployment_id!r}, not {route.deployment_id!r}"
            )
        if worker.topology_generation != route.topology_generation:
            raise ValueError(
                f"{label} worker {worker.worker_id!r} belongs to topology "
                f"generation {worker.topology_generation}, not "
                f"{route.topology_generation}"
            )
        if worker.dp_group_id != route.dp_group_id:
            raise ValueError(
                f"{label} worker {worker.worker_id!r} belongs to DP group "
                f"{worker.dp_group_id!r}, not {route.dp_group_id!r}"
            )
        worker.validate_format(format_manifest)

    selected_workers = tuple(
        worker for worker in workers if worker.dp_rank == route.dp_rank
    )
    if not selected_workers:
        raise ValueError(
            f"{label} DP route {route.dp_group_id!r}/{route.dp_rank} has no workers"
        )
    dp_sizes = {worker.dp_size for worker in workers}
    if len(dp_sizes) != 1:
        raise ValueError(f"{label} workers advertise inconsistent DP topology")
    if route.dp_rank >= next(iter(dp_sizes)):
        raise ValueError(f"{label} DP route is outside the advertised DP topology")
    selected_ranks = [worker.rank for worker in selected_workers]
    if len(set(selected_ranks)) != len(selected_ranks):
        raise ValueError(f"{label} DP route has duplicate transport ranks")

    # A plan must be formed from the complete selected replica, not merely a
    # common subset of source and destination workers.  DCP and EP are overlay
    # coordinates in vLLM: they do not create additional KV-owning processes.
    # The concrete placement membership is therefore PP x PCP x TP after DP
    # routing.  Checking the exact coordinate set prevents two independently
    # incomplete endpoint advertisements from composing into an apparently
    # complete (but silently truncated) plan.
    topology_sizes = {
        (
            worker.tp_size,
            worker.pcp_size,
            worker.pp_size,
            worker.dp_size,
        )
        for worker in selected_workers
    }
    if len(topology_sizes) != 1:
        raise ValueError(f"{label} workers advertise inconsistent topology sizes")
    tp_size, pcp_size, pp_size, _ = next(iter(topology_sizes))
    actual_coordinates = [
        (worker.pp_rank, worker.pcp_rank, worker.tp_rank) for worker in selected_workers
    ]
    if len(set(actual_coordinates)) != len(actual_coordinates):
        raise ValueError(f"{label} DP route has duplicate placement coordinates")
    expected_coordinates = set(product(range(pp_size), range(pcp_size), range(tp_size)))
    if set(actual_coordinates) != expected_coordinates:
        missing = sorted(expected_coordinates - set(actual_coordinates))
        unexpected = sorted(set(actual_coordinates) - expected_coordinates)
        raise ValueError(
            f"{label} DP route has incomplete placement membership: "
            f"missing={missing}, unexpected={unexpected}"
        )

    # PP owns layers while PCP and TP jointly describe the complete local
    # placement of every layer. Validate that invariant once at endpoint bind
    # time so malformed wire cohorts cannot produce request/page-dependent
    # partial plans.
    expected_layers = {
        layer_name
        for group in format_manifest.groups
        for layer_name in group.layer_names
    }
    layer_coordinates: dict[str, set[tuple[int, int, int]]] = defaultdict(set)
    for worker in selected_workers:
        coordinate = (worker.pp_rank, worker.pcp_rank, worker.tp_rank)
        for layer_mapping in worker.mappings:
            layer_coordinates[layer_mapping.layer_name].add(coordinate)
    actual_layers = set(layer_coordinates)
    if actual_layers != expected_layers:
        raise ValueError(
            f"{label} endpoint has incomplete layer ownership: "
            f"missing={sorted(expected_layers - actual_layers)}, "
            f"unexpected={sorted(actual_layers - expected_layers)}"
        )
    for layer_name, coordinates in layer_coordinates.items():
        owner_pp_ranks = {pp_rank for pp_rank, _, _ in coordinates}
        if len(owner_pp_ranks) != 1:
            raise ValueError(
                f"{label} layer {layer_name!r} must be owned by exactly one PP rank"
            )
        owner_pp_rank = next(iter(owner_pp_ranks))
        expected_layer_coordinates = {
            (owner_pp_rank, pcp_rank, tp_rank)
            for pcp_rank in range(pcp_size)
            for tp_rank in range(tp_size)
        }
        if coordinates != expected_layer_coordinates:
            missing = sorted(expected_layer_coordinates - coordinates)
            unexpected = sorted(coordinates - expected_layer_coordinates)
            raise ValueError(
                f"{label} layer {layer_name!r} has incomplete PCP/TP placement: "
                f"missing={missing}, unexpected={unexpected}"
            )

    seen_page_keys: set[tuple[str, str, int]] = set()
    selected_worker_ids = {worker.worker_id for worker in selected_workers}
    selected_pages: list[LocalPageAllocation] = []
    for page in pages:
        if page.key in seen_page_keys:
            raise ValueError(f"{label} endpoint has duplicate page key {page.key!r}")
        seen_page_keys.add(page.key)
        page_worker = workers_by_id.get(page.worker_id)
        if page_worker is None:
            raise ValueError(f"{label} page {page.key!r} references an unknown worker")
        if page.worker_incarnation != page_worker.worker_incarnation:
            raise ValueError(
                f"{label} page {page.key!r} belongs to stale worker incarnation "
                f"{page.worker_incarnation!r}"
            )
        if _mapping_for_layer(page_worker, page.layer_name) is None:
            raise ValueError(
                f"{label} page {page.key!r} references a layer not owned by its worker"
            )
        if page.worker_id in selected_worker_ids:
            selected_pages.append(page)

    return _BoundEndpoint(
        format_manifest=format_manifest,
        route=route,
        workers=selected_workers,
        pages=tuple(selected_pages),
    )


def _layer_owners(
    label: str,
    endpoint: _BoundEndpoint,
    layer_name: str,
    semantic_group_id: str,
) -> tuple[tuple[RankPlacementManifest, LayerPageMapping], ...]:
    owners: list[tuple[RankPlacementManifest, LayerPageMapping]] = []
    for worker in endpoint.workers:
        layer_mapping = _mapping_for_layer(worker, layer_name)
        if layer_mapping is None:
            continue
        if layer_mapping.semantic_group_id != semantic_group_id:
            raise ValueError(
                f"{label} layer {layer_name!r} is bound to semantic group "
                f"{layer_mapping.semantic_group_id!r}, not {semantic_group_id!r}"
            )
        owners.append((worker, layer_mapping))
    if not owners:
        raise ValueError(
            f"{label} DP route does not cover requested layer {layer_name!r}"
        )
    return tuple(owners)


def _mapping_owns_tokens(
    mapping: CanonicalPageMapping,
    page_first_token: int,
    first_token: int,
    end_token: int,
) -> bool:
    """Return whether a rank mapping owns bytes in a token interval."""
    for run in mapping.runs:
        token_stride = mapping.token_stride(run.canonical_region)
        interval_start = (first_token - page_first_token) * token_stride
        interval_end = (end_token - page_first_token) * token_stride
        if run.canonical_stride == 0:
            if (
                run.canonical_offset < interval_end
                and interval_start < run.canonical_offset + run.fragment_size
            ):
                return True
            continue
        first_candidate = max(
            0,
            (interval_start - run.canonical_offset - run.fragment_size)
            // run.canonical_stride
            + 1,
        )
        if (
            first_candidate < run.num_fragments
            and run.canonical_offset + first_candidate * run.canonical_stride
            < interval_end
        ):
            return True
    return False


def _require_layer_page_coverage(
    label: str,
    layer_name: str,
    owners: Sequence[tuple[RankPlacementManifest, LayerPageMapping]],
    pages_by_worker: dict[str, list[LocalPageAllocation]],
    ranges: Sequence[KVRange],
    *,
    sources: bool,
) -> None:
    page_spans = {
        layer_mapping.mapping.canonical_token_span for _, layer_mapping in owners
    }
    if None in page_spans or len(page_spans) != 1:
        raise ValueError(
            f"{label} layer {layer_name!r} has inconsistent canonical token geometry"
        )
    page_span = page_spans.pop()
    assert page_span is not None

    page_indices: dict[int, set[int]] = defaultdict(set)
    for worker, _ in owners:
        intervals: list[tuple[int, int]] = []
        for page in pages_by_worker[worker.worker_id]:
            intervals.append((page.first_token, page.first_token + page_span))
            page_indices[page.first_token].add(page.canonical_page_index)
        previous_end: int | None = None
        for start, end in sorted(intervals):
            if previous_end is not None and start < previous_end:
                raise ValueError(
                    f"{label} worker {worker.worker_id!r} has overlapping pages for "
                    f"layer {layer_name!r}"
                )
            previous_end = end

    inconsistent_indices = sorted(
        first_token
        for first_token, indices in page_indices.items()
        if len(indices) != 1
    )
    if inconsistent_indices:
        raise ValueError(
            f"{label} layer {layer_name!r} has inconsistent canonical page "
            f"indices at tokens {inconsistent_indices}"
        )
    logical_pages = {
        first_token: next(iter(indices))
        for first_token, indices in page_indices.items()
    }

    for kv_range in ranges:
        cursor = kv_range.first_token
        end = kv_range.valid_end_token
        if cursor == end:
            continue
        for page_start in sorted(logical_pages):
            page_end = page_start + page_span
            if page_end <= cursor:
                continue
            if page_start > cursor:
                break
            cursor = max(cursor, page_end)
            if cursor >= end:
                break
        if cursor < end:
            raise ValueError(
                f"{label} is missing page coverage for layer "
                f"{layer_name!r} at token {cursor}"
            )

    for page_first_token, page_index in logical_pages.items():
        page_end_token = page_first_token + page_span
        valid_intervals = [
            (
                max(page_first_token, kv_range.first_token),
                min(page_end_token, kv_range.valid_end_token),
            )
            for kv_range in ranges
            if max(page_first_token, kv_range.first_token)
            < min(page_end_token, kv_range.valid_end_token)
        ]
        if not valid_intervals:
            continue
        for worker, layer_mapping in owners:
            if sources and not layer_mapping.mapping.is_writer(page_index):
                continue
            owns_valid_bytes = any(
                _mapping_owns_tokens(
                    layer_mapping.mapping,
                    page_first_token,
                    first_token,
                    end_token,
                )
                for first_token, end_token in valid_intervals
            )
            if not owns_valid_bytes:
                continue
            has_page = any(
                page.first_token == page_first_token
                and page.canonical_page_index == page_index
                for page in pages_by_worker[worker.worker_id]
            )
            if not has_page:
                raise ValueError(
                    f"{label} worker {worker.worker_id!r} is missing page coverage "
                    f"for layer {layer_name!r} at token {page_first_token}"
                )


def _placements_for_layer(
    label: str,
    endpoint: _BoundEndpoint,
    layer_name: str,
    semantic_group_id: str,
    ranges: Sequence[KVRange],
    *,
    sources: bool,
) -> tuple[PagePlacement, ...]:
    owners = _layer_owners(label, endpoint, layer_name, semantic_group_id)
    pages_by_worker: dict[str, list[LocalPageAllocation]] = defaultdict(list)
    for page in endpoint.pages:
        if page.layer_name == layer_name:
            pages_by_worker[page.worker_id].append(page)

    placements: list[PagePlacement] = []
    canonical_space_id = endpoint.format_manifest.canonical_space_id(semantic_group_id)
    _require_layer_page_coverage(
        label,
        layer_name,
        owners,
        pages_by_worker,
        ranges,
        sources=sources,
    )
    for worker, layer_mapping in owners:
        mapping = layer_mapping.mapping
        page_span = mapping.canonical_token_span
        if page_span is None:
            raise ValueError(
                f"{label} layer {layer_name!r} has no canonical token geometry"
            )
        worker_pages = pages_by_worker[worker.worker_id]
        for page in worker_pages:
            page_end = page.first_token + page_span
            for kv_range in ranges:
                first_token = max(page.first_token, kv_range.first_token)
                end_token = min(page_end, kv_range.valid_end_token)
                if first_token >= end_token:
                    continue
                placements.append(
                    PagePlacement(
                        rank=worker.rank,
                        local_page_id=page.local_page_id,
                        canonical_page_index=page.canonical_page_index,
                        mapping=mapping,
                        canonical_space_id=canonical_space_id,
                        first_token=page.first_token,
                        valid_token_offset=first_token - page.first_token,
                        valid_token_count=end_token - first_token,
                        local_base=page.local_base,
                    )
                )
    return tuple(placements)


def _layer_index(
    label: str,
    owners: Sequence[tuple[RankPlacementManifest, LayerPageMapping]],
    layer_name: str,
) -> int:
    indices = {layer_mapping.layer_index for _, layer_mapping in owners}
    if len(indices) != 1:
        raise ValueError(
            f"{label} workers disagree on the index of layer {layer_name!r}"
        )
    return indices.pop()


def build_request_transfer_context(
    *,
    source_format: KVFormatManifest,
    destination_format: KVFormatManifest,
    source_route: EndpointRoute,
    destination_route: EndpointRoute,
    source_workers: Sequence[RankPlacementManifest],
    destination_workers: Sequence[RankPlacementManifest],
    ranges: Sequence[KVRange],
) -> RequestTransferContext:
    """Validate compact request metadata without materializing page copies.

    Groups are matched by semantic identity, never endpoint-local group order.
    DP chooses one replica on each endpoint. PP ownership emerges from the
    workers advertising each layer; EP coordinates are diagnostic only.
    """
    source = _bind_endpoint("source", source_format, source_route, source_workers, ())
    destination = _bind_endpoint(
        "destination",
        destination_format,
        destination_route,
        destination_workers,
        (),
    )
    ranges = validate_kv_ranges(ranges, source_format)
    ranges_by_group: dict[str, list[KVRange]] = defaultdict(list)
    for kv_range in ranges:
        ranges_by_group[kv_range.semantic_group_id].append(kv_range)

    layers: list[RequestLayerSpec] = []
    for semantic_group_id, group_ranges in ranges_by_group.items():
        source_group = source_format.semantic_group(semantic_group_id)
        destination_group = destination_format.semantic_group(semantic_group_id)
        source_space = source_format.canonical_space_id(semantic_group_id)
        destination_space = destination_format.canonical_space_id(semantic_group_id)
        if source_space != destination_space:
            raise ValueError(
                f"semantic KV group {semantic_group_id!r} uses incompatible "
                "canonical spaces"
            )
        if not any(kv_range.valid_token_count for kv_range in group_ranges):
            continue

        for layer_name in source_group.layer_names:
            source_owners = _layer_owners(
                "source", source, layer_name, semantic_group_id
            )
            destination_owners = _layer_owners(
                "destination", destination, layer_name, semantic_group_id
            )
            source_index = _layer_index("source", source_owners, layer_name)
            destination_index = _layer_index(
                "destination", destination_owners, layer_name
            )
            if source_index != destination_index:
                raise ValueError(
                    f"source and destination disagree on the index of layer "
                    f"{layer_name!r}"
                )
            layers.append(
                RequestLayerSpec(
                    layer_name=layer_name,
                    layer_index=source_index,
                    semantic_group_id=semantic_group_id,
                    source_group_id=source_group.group_id,
                    destination_group_id=destination_group.group_id,
                )
            )

    layer_specs = tuple(
        sorted(
            layers,
            key=lambda layer: (
                layer.layer_index,
                layer.semantic_group_id,
                layer.layer_name,
            ),
        )
    )
    source_participants = tuple(
        WorkerIdentity(worker.worker_id, worker.worker_incarnation)
        for worker in sorted(source.workers, key=lambda worker: worker.worker_id)
    )
    destination_participants = tuple(
        WorkerIdentity(worker.worker_id, worker.worker_incarnation)
        for worker in sorted(destination.workers, key=lambda worker: worker.worker_id)
    )
    return RequestTransferContext(
        source_format=source.format_manifest,
        destination_format=destination.format_manifest,
        source_route=source.route,
        destination_route=destination.route,
        source_workers=source.workers,
        destination_workers=destination.workers,
        ranges=ranges,
        layers=layer_specs,
        source_participants=source_participants,
        destination_participants=destination_participants,
    )


def _request_transfer_layer_placements(
    context: RequestTransferContext,
    layer: RequestLayerSpec,
    *,
    source_pages: Sequence[LocalPageAllocation],
    destination_pages: Sequence[LocalPageAllocation],
    ranges: Sequence[KVRange] | None,
    destination_rank: int | None = None,
) -> tuple[tuple[PagePlacement, ...], tuple[PagePlacement, ...]]:
    """Bind and validate a connector-provided layer/page window."""
    if not isinstance(context, RequestTransferContext):
        raise ValueError("context must be a RequestTransferContext")
    if not isinstance(layer, RequestLayerSpec) or layer not in context.layers:
        raise ValueError("layer must belong to the request transfer context")
    if ranges is None:
        layer_ranges = tuple(
            kv_range
            for kv_range in context.ranges
            if kv_range.semantic_group_id == layer.semantic_group_id
        )
    else:
        layer_ranges = tuple(ranges)
        for kv_range in layer_ranges:
            if kv_range.semantic_group_id != layer.semantic_group_id:
                raise ValueError("layer window contains a different semantic KV group")
            if not any(
                kv_range.first_token >= request_range.first_token
                and kv_range.valid_end_token <= request_range.valid_end_token
                for request_range in context.ranges
                if request_range.semantic_group_id == layer.semantic_group_id
            ):
                raise ValueError("layer window is outside the request token coverage")

    source = _bind_endpoint(
        "source",
        context.source_format,
        context.source_route,
        context.source_workers,
        source_pages,
    )
    destination = _bind_endpoint(
        "destination",
        context.destination_format,
        context.destination_route,
        context.destination_workers,
        destination_pages,
    )
    source_placements = _placements_for_layer(
        "source",
        source,
        layer.layer_name,
        layer.semantic_group_id,
        layer_ranges,
        sources=True,
    )
    destination_placements = _placements_for_layer(
        "destination",
        destination,
        layer.layer_name,
        layer.semantic_group_id,
        layer_ranges,
        sources=False,
    )
    if destination_rank is not None:
        _require_nonnegative_int(destination_rank, "destination_rank")
        destination_ranks = {worker.rank for worker in destination.workers}
        if destination_rank not in destination_ranks:
            raise ValueError(
                f"destination_rank {destination_rank} is not a request participant"
            )
        # Deliberately filter only after _placements_for_layer validates every
        # owner/allocation. A local worker must not hide an incomplete remote
        # destination cohort by asking for only its own copies.
        destination_placements = tuple(
            placement
            for placement in destination_placements
            if placement.rank == destination_rank
        )
    return source_placements, destination_placements


def plan_request_transfer_layer(
    context: RequestTransferContext,
    layer: RequestLayerSpec,
    *,
    source_pages: Sequence[LocalPageAllocation],
    destination_pages: Sequence[LocalPageAllocation],
    ranges: Sequence[KVRange] | None = None,
) -> LayerTransferPlan:
    """Compose one layer from a connector-provided bounded page window."""
    source_placements, destination_placements = _request_transfer_layer_placements(
        context,
        layer,
        source_pages=source_pages,
        destination_pages=destination_pages,
        ranges=ranges,
    )
    return LayerTransferPlan(
        layer_name=layer.layer_name,
        layer_index=layer.layer_index,
        semantic_group_id=layer.semantic_group_id,
        source_group_id=layer.source_group_id,
        destination_group_id=layer.destination_group_id,
        runs=compose_page_placements(source_placements, destination_placements),
    )


def iter_request_transfer_layer_runs(
    context: RequestTransferContext,
    layer: RequestLayerSpec,
    *,
    source_pages: Sequence[LocalPageAllocation],
    destination_pages: Sequence[LocalPageAllocation],
    ranges: Sequence[KVRange] | None = None,
    max_buffered_copy_fragments: int = 4096,
    destination_rank: int | None = None,
) -> Iterator[TransferRun]:
    """Stream one layer's direct runs with bounded composition memory.

    This validates the same page window as :func:`plan_request_transfer_layer`
    but does not materialize the layer-wide expanded fragments, copy
    fragments, or run tuple. Fragmentation only creates more yielded direct
    runs.
    """
    source_placements, destination_placements = _request_transfer_layer_placements(
        context,
        layer,
        source_pages=source_pages,
        destination_pages=destination_pages,
        ranges=ranges,
        destination_rank=destination_rank,
    )
    yield from iter_page_placement_transfer_runs(
        source_placements,
        destination_placements,
        max_buffered_copy_fragments=max_buffered_copy_fragments,
    )


def build_request_transfer_plan(
    *,
    source_format: KVFormatManifest,
    destination_format: KVFormatManifest,
    source_route: EndpointRoute,
    destination_route: EndpointRoute,
    source_workers: Sequence[RankPlacementManifest],
    destination_workers: Sequence[RankPlacementManifest],
    source_pages: Sequence[LocalPageAllocation],
    destination_pages: Sequence[LocalPageAllocation],
    ranges: Sequence[KVRange],
) -> RequestTransferPlan:
    """Plan direct segmented copies and completion participants for a request.

    This eager convenience API remains useful for standalone connectors and
    tests. Runtime connectors with large requests should retain the compact
    context and call :func:`plan_request_transfer_layer` incrementally.
    """
    context = build_request_transfer_context(
        source_format=source_format,
        destination_format=destination_format,
        source_route=source_route,
        destination_route=destination_route,
        source_workers=source_workers,
        destination_workers=destination_workers,
        ranges=ranges,
    )
    bound_source = _bind_endpoint(
        "source", source_format, source_route, source_workers, source_pages
    )
    bound_destination = _bind_endpoint(
        "destination",
        destination_format,
        destination_route,
        destination_workers,
        destination_pages,
    )
    layers = tuple(
        plan_request_transfer_layer(
            context,
            layer,
            source_pages=bound_source.pages,
            destination_pages=bound_destination.pages,
        )
        for layer in context.layers
    )
    return RequestTransferPlan(
        layers=layers,
        source_route=context.source_route,
        destination_route=context.destination_route,
        source_participants=context.source_participants,
        destination_participants=context.destination_participants,
    )


def plan_request_transfers(
    *,
    source_format: KVFormatManifest,
    destination_format: KVFormatManifest,
    source_route: EndpointRoute,
    destination_route: EndpointRoute,
    source_workers: Sequence[RankPlacementManifest],
    destination_workers: Sequence[RankPlacementManifest],
    source_pages: Sequence[LocalPageAllocation],
    destination_pages: Sequence[LocalPageAllocation],
    ranges: Sequence[KVRange],
) -> tuple[LayerTransferPlan, ...]:
    """Return the per-layer runs from :func:`build_request_transfer_plan`."""
    return build_request_transfer_plan(
        source_format=source_format,
        destination_format=destination_format,
        source_route=source_route,
        destination_route=destination_route,
        source_workers=source_workers,
        destination_workers=destination_workers,
        source_pages=source_pages,
        destination_pages=destination_pages,
        ranges=ranges,
    ).layers


__all__ = [
    "EndpointRoute",
    "LayerTransferPlan",
    "LocalPageAllocation",
    "RequestLayerSpec",
    "RequestTransferContext",
    "RequestTransferPlan",
    "build_request_transfer_context",
    "build_request_transfer_plan",
    "iter_request_transfer_layer_runs",
    "plan_request_transfer_layer",
    "plan_request_transfers",
]
